# Generated by Django 4.2 on 2023-05-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dec', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
